---
version: 2
jobs:
    test:
        working_directory: ~/circleci-locarise-drf-oauth2-support
        docker:
            - image: circleci/python:3.7
              environment:
                  DATABASE_URL: postgres://username:pass@127.0.0.1:5432/somedb
            - image: circleci/postgres:9.6.11
              environment:
                  POSTGRES_USER: username
                  POSTGRES_PASSWORD: pass
                  POSTGRES_DB: somedb
            - image: circleci/redis:5.0.5
        steps:
            - checkout
            - run:
                command: |
                    python setup.py install --user
                    pip install --user -r tests/requirements.txt
                    python manage.py test
workflows:
    version: 2
    test:
        jobs:
            - test:
                filters:
                  branches:
                      only:
                          - master
                          - develop
