# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 08:54
from __future__ import unicode_literals

try:
    from django.contrib.postgres.fields.jsonb import JSONField
except ImportError:  # pragma: no cover
    from jsonfield import JSONField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160719_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_set',
            field=JSONField(null=True),
        ),
    ]
