# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_organization_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organization_set',
            new_name='organizations',
        ),
    ]
